### ISSUE TITLE
Add non-breaking space in file size descriptor

### ISSUE THREAD

**Issue by jgorres** [eagerterrier/MimeTypes-Link-Icons#15]
Hi,

I think, for a neater layout it may be a nice thing to add a non-breaking space (&nbsp;) between the figures and the file size unit in order to keep them together.

I.e. <CODE>999<&nbsp;>kB</CODE>

This will prevent that figure and unit are splitted on different lines.

Thanks,
Jörn.

**Comment by jrfnl** [comment]
While I appreciate the suggestion, this is impossible with how the filesize text is currently added to the page through css. Adding a `&nbsp;` would literally add that string to the text on your screen (believe me: I just tested it).

You could add a css rule for mtli influenced linked to `white-space: nowrap;` but that would influence the whole of the link, not just the filesize string.

**Comment by jrfnl** [comment]
The only thing I can suggest for now would be to filter the string and remove the space all together:

```php
function no_space_in_mtli_filesize( $string ) {
	return str_replace( ' ', '', $string );
}
add_filter( 'mtli_filesize', 'no_space_in_mtli_filesize' );
```
