### ISSUE TITLE
Add licensing info

### ISSUE THREAD

**Issue by jrfnl** [eagerterrier/MimeTypes-Link-Icons#25]
https://wordpress.org/support/topic/licensing-of-icons?replies=1

Either add a LICENSE file or add icon licensing info to the readme to clarify whether re-use of the icons outside of the plugin is allowed.

**Comment by zoechi** [comment]
Any update on this?
They are quite nice icons.

**Comment by eagerterrier** [comment]
It's tricky. Essentially I've made up any that didn't already exist and then used any further icons where the terms allow, so each image would have to have its own licence.
