### ISSUE TITLE
Update to show compatability with WP 5.X?

### ISSUE THREAD

**Issue by markmacallister** [eagerterrier/MimeTypes-Link-Icons#33]
Greetings and thanks so much for this useful plugin?

Will you be updating this plugin so that it is confirmed to work with WP 5.X? It is a useful plugin but I won’t be able to use it much longer without an update showing compatability with 5.X.

With all respect, it’s not a function of any problems with the plugin working in WP 5.X. To the best of my knowledge, the plugin has not generated any errors on my site.

Rather, my concern is that my WordFence security setup tends to flag plugins that haven’t been updated or otherwise maintained over a certain period of time. WF considers them essentially abandoned, or at least incompatible, and recommends removal. Since the banner for your plugin on WordPress.com reads “This plugin hasn’t been tested with the latest 3 major releases of WordPress. It may no longer be maintained or supported and may have compatibility issues when used with more recent versions of WordPress,” it made me curious about the plugin’s status.

It may be that you can just touch the file as a gesture towards update and that will make everything happy. I wouldn’t ask you to do any significant work, but I did want to check to make sure that the plugin indeed has not been abandoned. I does not appear that the plugin is abandoned, but it would still be cool to know for sure that the plugin is current and for WordPress.com to reflect that status.

Please let me know if you have any other questions. Thanks again!

**Comment by redbarndesign** [comment]
Thanks for posting, Mark. This is a very useful plugin and would like to use it on a project, but wasn't sure if it was abandoned. Credit to whoever created it!

**Comment by eagerterrier** [comment]
sorry guys.

I moved to a new job 15 months ago and haven't been able to be on top of this plugin as much as I would like. My new role is more front end with no PHP, so I have to dust off those skills!

I'll try and take a look at this over the next few weeks...

**Comment by redbarndesign** [comment]
No worries, EagerTerrier. Thanks for replying. Hopefully, time can be made for WP5.x compatibility. Congrats on your new job!

**Comment by now4dw** [comment]
Good morning @eagerterrier. I'm wondering if you've been able to move forward on this issue?

**Comment by markmacallister** [comment]
Greetings EagerTerrier, I hope things are well. Just last night I received notice via my WordFence installation that MimeTypes Link Icon appears abandoned as it only shows tested to WP 4.7.14. I am running WP 5.2.3 and the plugin appears to be running with no problems. If it is at all possible for you to put a touch on this plugin so that it reflects "up to date" status for WordPress.com (and for WordFence), I'm sure many of us would be grateful. Thanks so much for anything you might be able to do!

Best,

Mark MacAllister
Pittsboro NC

**Comment by eagerterrier** [comment]
sorry all - we did this, but forgot to reply on github. Let me know if there are any more issues. Thanks
