### ISSUE TITLE
3.2.18 causes an error when saving in the Gutenberg block editor

### ISSUE THREAD

**Issue by teebee** [eagerterrier/MimeTypes-Link-Icons#37]
This [fix](https://github.com/eagerterrier/MimeTypes-Link-Icons/commit/56688dd66e55918d2a1c391506b0273480819d40#diff-42d308ed7717999a73ca2e7dd25c02a39e2407df027df76dd444e3b6cf1013cdL1313) causes an error when saving in the Gutenberg block editor: some (identical) style tags are added to the JSON result:
```
$ curl -sL 'https://localhost/wp-json/wp/v2/posts/8128?_locale=user' -X POST -H 'X-WP-Nonce: XXX' -H 'Content-Type: application/json' -H 'Cookie: wordpress_logged_in_XXX' --data-raw '{"id":8128,"content":"<!-- wp:paragraph -->\n<p>this is a <a href=\"https://.pdf\" target=\"_blank\" rel=\"noreferrer noopener\">test</a></p>\n<!-- /wp:paragraph -->"}'
<style type="text/css">a[data-mtli~="mtli_filesize4,00kB"]:after {content:" (4,00 kB)"}</style><style type="text/css">a[data-mtli~="mtli_filesize4,00kB"]:after {content:" (4,00 kB)"}</style> [...] {"id":8128,"date":"2024-03-08T21:14:38","date_gmt":"2024-03-08T20:14:38" [...]
```
Unfortunately, the reason for the _FIX: bug fix_ is not stated. However, it is likely that the plugin should not be active at all while editing a post, which is also what [mime_type_link_images.php#L712](https://github.com/eagerterrier/MimeTypes-Link-Icons/blob/master/mime_type_link_images.php#L712) suggests. Note that `is_admin()` will return `false` when using the block editor (see: [ticket #47394](https://core.trac.wordpress.org/ticket/47394).)

So, maybe adding
```
if ( wp_is_json_request() ) {
	return $content;
}
```
at the beginning of [mime_type_link_images.php#L1191](https://github.com/eagerterrier/MimeTypes-Link-Icons/blob/master/mime_type_link_images.php#L1191) is a solution.

Could you take a look at it, please ?

**Comment by eagerterrier** [comment]
hey - I'm not seeing this on my live blog.

<img width="1095" alt="Screenshot 2024-03-10 at 16 13 23" src="https://github.com/eagerterrier/MimeTypes-Link-Icons/assets/91352/4875e493-2c6d-4ae4-89f0-55c54bbfb9a9">

Can you give a bit more info? 

What version of WP, what version of plugin, where the curl is coming from (presumably copy request as curl in chrome?) etc - as much detail as you can would be great

(e.g. I just had to disable 10 old plugins on my site just to get guttenberg to load without flashing 10 times a second)

**Comment by teebee** [comment]
The problem occurs, for example, with Wordpress `6.4.3` and MimeTypes Link Icons `3.2.18` when you display the file size of an attachment/linked file. You should be allowed to [register](https://eagerterrier.de.cool/wp-login.php?action=register) on https://eagerterrier.de.cool and investigate the error yourself. Does it help?

**Comment by eagerterrier** [comment]
hey @teebee - thanks for this. Sounds very helpful, but I've tried to register but I've received no email. Not in junk folder either. I've waited 10m or so. Maybe gmail is stopping it from arriving. Any chance you can approve me and send me a password? Thanks!

**Comment by eagerterrier** [comment]
ok - 3.2.19 has gone up. That should fix it. Can you confirm?

**Comment by teebee** [comment]
LGTM. Thank you for fixing and releasing a new version.
